modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/SrRapero720/watermedia/issues" #optional
[[mods]] #mandatory
modId="watermedia" #mandatory
version="${file.jarVersion}" #mandatory
displayName="WATERMeDIA" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/watermedia" #optional
logoFile="examplemod.png" #optional
credits="This VLCJ discovery is possible by CreativeMD" #optional
authors="SrRapero720 and Goedix" #optional
description='''
Multimedia Power!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.watermedia]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"
